name: Deploy to cPanel

on:
  push:
    tags:
      - 'version-*'
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run gulp
      run: npm run gulp

    - name: Install FTP deployment tool
      run: sudo apt-get install -y lftp

    - name: Deploy to cPanel
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        lftp -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST <<EOF
        mirror -R ./dist /path/on/cpanel
        bye
        EOF
